// Presets named by intended listening use. Wellness intentions, not medical promises.
const FREQUENCIES = [
 {hz:432,emoji:'🎻',color:'#f5b971',en:{name:'Relaxed Listening',tag:'Calm',desc:'A warm, slightly lower tuning for relaxed listening, winding down and quiet evenings.'},de:{name:'Entspannt hören',tag:'Ruhe',desc:'Eine warme, leicht tiefere Stimmung für entspanntes Musikhören, Abschalten und ruhige Abende.'}},
 {hz:174,emoji:'🌿',color:'#8fbf6a',en:{name:'Deep Relaxation',tag:'Unwind',desc:'Choose this preset when you want to slow down, release tension and settle.'},de:{name:'Tiefe Entspannung',tag:'Runterkommen',desc:'Wähle dieses Preset zum Runterkommen, zum Lösen von Anspannung und für mehr Ruhe.'}},
 {hz:285,emoji:'🌱',color:'#5fc29b',en:{name:'Rest & Recovery',tag:'Recovery',desc:'For rest breaks, power naps and calm recovery after a demanding day or workout.'},de:{name:'Erholung',tag:'Regeneration',desc:'Für Ruhepausen, Power-Naps und entspanntes Erholen nach einem anstrengenden Tag oder Sport.'}},
 {hz:396,emoji:'🕊️',color:'#e07a7a',en:{name:'Letting Go',tag:'Release',desc:'A listening intention for evening routines, journaling and clearing a busy mind.'},de:{name:'Loslassen',tag:'Entlastung',desc:'Eine Hörintention für Abendroutine, Journaling und um einen vollen Kopf zur Ruhe zu bringen.'}},
 {hz:417,emoji:'🔄',color:'#f09a5b',en:{name:'Fresh Start',tag:'Motivation',desc:'Use for a reset, a new task, decluttering or when you want fresh momentum.'},de:{name:'Neustart',tag:'Motivation',desc:'Für einen Reset, eine neue Aufgabe, zum Ausmisten oder wenn du frischen Schwung möchtest.'}},
 {hz:528,emoji:'💚',color:'#6fd17a',en:{name:'Positive Mood & Creativity',tag:'Create',desc:'A bright listening intention for creative work, optimism and an uplifting atmosphere.'},de:{name:'Positive Stimmung & Kreativität',tag:'Kreativität',desc:'Eine helle Hörintention für kreatives Arbeiten, Optimismus und eine aufbauende Atmosphäre.'}},
 {hz:639,emoji:'🤝',color:'#ef8fc0',en:{name:'Connection',tag:'Together',desc:'For shared time, open conversations and a warm, connected atmosphere.'},de:{name:'Verbundenheit',tag:'Miteinander',desc:'Für gemeinsame Zeit, offene Gespräche und eine warme, verbundene Atmosphäre.'}},
 {hz:741,emoji:'🎯',color:'#5fb6f0',en:{name:'Focus & Clarity',tag:'Deep Work',desc:'The work preset for studying, coding, problem solving and sustained concentration.'},de:{name:'Fokus & Klarheit',tag:'Deep Work',desc:'Das Arbeits-Preset für Lernen, Programmieren, Problemlösen und längere Konzentration.'}},
 {hz:852,emoji:'👁️',color:'#8f8cf2',en:{name:'Mindful Concentration',tag:'Mindfulness',desc:'For reflection, calm attention, meditation and focused breathing.'},de:{name:'Achtsame Konzentration',tag:'Achtsamkeit',desc:'Für Reflexion, ruhige Aufmerksamkeit, Meditation und konzentriertes Atmen.'}},
 {hz:963,emoji:'✨',color:'#c79bf7',en:{name:'Deep Meditation',tag:'Stillness',desc:'The quiet preset for meditation, yoga, contemplation and intentional silence.'},de:{name:'Tiefe Meditation',tag:'Stille',desc:'Das ruhige Preset für Meditation, Yoga, Kontemplation und bewusste Stille.'}}
];
const NOTE_NAMES={en:['A','A♯','B','C','C♯','D','D♯','E','F','F♯','G','G♯'],de:['A','A♯','H','C','C♯','D','D♯','E','F','F♯','G','G♯']};
function noteName(n,lang){const idx=((n%12)+12)%12;return(NOTE_NAMES[lang]||NOTE_NAMES.en)[idx]+(4+Math.floor((n+9)/12));}
function tuningFor(hz,ref=440,lang='en'){const n=Math.round(12*Math.log2(hz/ref));const note=ref*Math.pow(2,n/12);const ratio=hz/note;return{source:note,target:hz,ratio,a4:ref*ratio,cents:1200*Math.log2(ratio),n,noteName:noteName(n,lang)};}
